Smile 1440 reduntant link
BIBSYSDEV/dlr-gui-new pull request #1086
Opened 2022-03-22 09:44 UTC by anetteOlli

2022-03-22 09:44 UTC, anetteOlli commented on src/components/ResultListItem.tsx
> +          <Link
Får fortsatt erroren, men nå skal ikke skjermleser brukere få lest opp lenka to ganger.

2022-03-22 13:25 UTC, pcb-unit requested changes

2022-03-22 13:25 UTC, pcb-unit commented on src/layout/header/Header.tsx
> +        <>
her kan fragmentet slankes bort

2022-03-23 13:19 UTC, anetteOlli commented on src/layout/header/Header.tsx
> +  const mediumOrSmallerScreen = useMediaQuery(`(max-width:${DeviceWidths.md}px)`);
fikset

2022-03-23 13:19 UTC, anetteOlli commented on src/layout/header/Header.tsx
> +        <>
fikset

2022-03-24 09:36 UTC, pcb-unit approved these changes

2022-03-24 10:14 UTC, merged