Smile 852 kaltura list
BIBSYSDEV/dlr-gui-new pull request #608
Opened 2021-07-05 06:53 UTC by pcb-unit

Jeg har ennå ikke fått til å opprette nye kaltura-videoer for å teste, men jeg legger ut koden enn så lenge

2021-07-05 12:54 UTC, anetteOlli requested changes

2021-07-05 12:54 UTC, anetteOlli commented on src/pages/edit_resource/EditResourcePage.tsx
> +      //TODO: placement "use" button for kaltura
Er disse TODO'sene gjort?

2021-07-05 12:54 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +                      <Link href={resultItem.url} target="_blank">
Her mangler rel=”noreferrer noopener”

2021-07-05 12:54 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              kalturaResources.map((resultItem) => (
Lage en egen kalturaResourceItem komponent?

2021-07-05 12:54 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +                      {resultItem.dlrContentIdentifier ? (
Hvis dlrContentIdentifier eksisterer så hadde det vært fint om man kunne hente ut ressurs-tittel til den, slik som vi gjør med arbeidslistene.

2021-07-05 12:54 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              <Typography>{t('Ingen ressurser funnet')}</Typography>
translation

2021-07-06 09:25 UTC, pcb-unit commented on src/pages/edit_resource/EditResourcePage.tsx
> +      //TODO: placement "use" button for kaltura
de er heldigvis gjort

2021-07-06 09:25 UTC, pcb-unit commented on src/pages/edit_resource/EditResourcePage.tsx
> +      //TODO: placement "use" button for kaltura
fikset

2021-07-06 09:28 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +                      <Link href={resultItem.url} target="_blank">
done

2021-07-06 09:30 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              <Typography>{t('Ingen ressurser funnet')}</Typography>
fixd

2021-07-06 09:33 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +                      {resultItem.dlrContentIdentifier ? (
Du har lyst å linke til ressursen om den finnes ? Tja - Jeg skjønner ikke helt hvorfor vi skal vise ressurser som finnes fra før i det hele tatt. Dette er jo en registrerings-side. Leggger vi inn mer logikk ødelegger vi iallefall flyten tenker jeg

2021-07-06 10:32 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              kalturaResources.map((resultItem) => (
ok, da

2021-07-06 10:34 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +                      {resultItem.dlrContentIdentifier ? (
Ser den

2021-07-06 10:35 UTC, anetteOlli approved these changes

2021-07-06 14:56 UTC, anetteOlli commented on cypress/integration/registration.spec.js
> +  });
![image](https://user-images.githubusercontent.com/44363838/124622031-091a6300-de7b-11eb-8621-edc41fdec643.png)
Ser ut som du har en bug i en av testene dine

2021-07-07 07:12 UTC, pcb-unit commented on cypress/integration/registration.spec.js
> +  });
jeg lot meg lure til å tro at det var noe aws-feil først og så ikke den reelle feilen.

2021-07-07 09:21 UTC, merged