Smile scroll to top after switching page
BIBSYSDEV/dlr-gui-new pull request #659
Opened 2021-08-03 10:14 UTC by anetteOlli

2021-08-09 12:42 UTC, pcb-unit requested changes

2021-08-09 12:42 UTC, pcb-unit commented on src/pages/dashboard/Explore.tsx
> +  const handlePaginationChange = useCallback(
Funker flott, men når vi scroller til toppen burde vi kanskje vist hvilken side vi er på. Enten med å bare vise en tekst eller ha en paginering på toppen også

2021-08-09 12:42 UTC, pcb-unit commented on src/pages/dashboard/Explore.tsx
> +                <StyledList ref={startOfList}>
synes kanskje refen burde ligget i listeheaderen (StyledResultListHeaderWrapper) isteden.

2021-08-10 10:02 UTC, anetteOlli commented on src/pages/dashboard/Explore.tsx
> +  const handlePaginationChange = useCallback(
Fikset

2021-08-10 10:02 UTC, anetteOlli commented on src/pages/dashboard/Explore.tsx
> +                <StyledList ref={startOfList}>
Fikset

2021-08-10 10:43 UTC, pcb-unit requested changes

2021-08-10 10:43 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +            <DialogContentText ref={startOfList}>
![image](https://user-images.githubusercontent.com/46489468/128852906-8b0889d3-b47f-4f2a-89db-8027fc3efe53.png)
Skille mellom result og "Viser ...". Parentes kanskje ?

2021-08-10 10:43 UTC, pcb-unit commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              <b>
Dessuten starter telleren på 0

2021-08-10 10:46 UTC, pcb-unit commented on src/pages/dashboard/Explore.tsx
> +                    {`${t('common.showing')} ${parseInt(searchResult.offset) + 1}-${
mindre mellomrom mellom "result" og "viser ..."

2021-08-10 13:25 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +            <DialogContentText ref={startOfList}>
Fikset

2021-08-10 13:25 UTC, anetteOlli commented on src/pages/edit_resource/KalturaRegistration.tsx
> +              <b>
Fikset

2021-08-10 13:25 UTC, anetteOlli commented on src/pages/dashboard/Explore.tsx
> +                    {`${t('common.showing')} ${parseInt(searchResult.offset) + 1}-${
Fikset

2021-08-11 08:10 UTC, pcb-unit approved these changes

2021-08-11 08:10 UTC, merged