Smile 454 autocapitalize input fields
BIBSYSDEV/dlr-gui-new pull request #666
Opened 2021-08-05 11:01 UTC by anetteOlli

2021-08-09 12:22 UTC, pcb-unit commented on src/pages/edit_resource/description_step/DescriptionFields.tsx
> +      const eventTargetValueFirstLetterUpperCase =
supert. Vi skulle vel nesten ha splittet denne. Dette er vel eneste plassen vi bruker en generisk saveField-metode ?

2021-08-09 13:40 UTC, anetteOlli commented on src/pages/edit_resource/description_step/DescriptionFields.tsx
> +      const eventTargetValueFirstLetterUpperCase =
Splittinga førte til veldig mye code duplisering. Har forbedret funksjonen noe slik at det er mindre logikk inni. Pluss bruk av konstanter er forbedret.

2021-08-10 07:51 UTC, pcb-unit approved these changes

2021-08-10 09:09 UTC, pcb-unit requested changes
Cypress-test ?

2021-08-10 12:55 UTC, pcb-unit approved these changes

2021-08-10 12:59 UTC, merged