Smile 480 vertical stepper
BIBSYSDEV/dlr-gui-new pull request #668
Opened 2021-08-06 11:19 UTC by anetteOlli

2021-08-09 12:00 UTC, pcb-unit requested changes

2021-08-09 12:06 UTC, anetteOlli commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
Fulgte figmaen til Stine

2021-08-09 12:11 UTC, anetteOlli commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
Skal eksperimentere med den litt

2021-08-09 12:17 UTC, pcb-unit commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
oi. De hadde jeg ikke sett :-) Da er det sikkert greit, ja

2021-08-09 12:53 UTC, anetteOlli commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
Mindre padding rundt teksten. Teksten matcher nå fargen til knappen over. Synes det ikke ser fint ut når jeg sentrerer teksten til midt under stepperen.

2021-08-09 12:53 UTC, anetteOlli commented on src/pages/edit_resource/ResourceForm.tsx
> +                {resource.features.dlr_title}
Bra observert, fikset

2021-08-09 12:57 UTC, pcb-unit commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
Det synes jeg ble veldig bra! Savner et par pixler padding mot kanten (samt for header og tittel) når skjermen er i mobilmodus

2021-08-10 07:37 UTC, anetteOlli commented on src/pages/edit_resource/SchemaPartTitle.tsx
> +            {stepTitle}
Fikset

2021-08-10 07:50 UTC, pcb-unit approved these changes

2021-08-10 10:02 UTC, merged