Smile 962 missing embed src url
BIBSYSDEV/dlr-gui-new pull request #689
Opened 2021-08-18 12:09 UTC by anetteOlli

2021-08-18 12:09 UTC, anetteOlli commented
Demo av flere iframes i canvas: https://bibsys.instructure.com/courses/197/pages/nye-dlr-test

2021-08-19 09:43 UTC, pcb-unit requested changes

2021-08-19 09:43 UTC, pcb-unit commented on src/components/ContentPreview.tsx
> +                {!user.id && (
kan vel forenkles til `user.id ? <typography>  : (<><typography><button></>) ;`

2021-08-19 09:43 UTC, pcb-unit commented on src/translations/translations_NO.json
> +      "your_user_does_not_have_access": "Brukeren din har ikke tilgang til dette innholdet"
"brukeren din" synes jeg ble litt rart ? har vi noe bedre

2021-08-19 12:33 UTC, pcb-unit requested changes

2021-08-19 12:33 UTC, pcb-unit commented on src/components/ContentPreview.tsx
> +                  <>
tomme tags trengs vel ikke

2021-08-19 12:52 UTC, pcb-unit approved these changes

2021-08-19 13:07 UTC, merged